# database/migrations/script.py.mako

"""Remove passwords and sessions

Revision ID: 9404acc3bc9d
Revises: 3a4b5c6d7e8f
Create Date: 2026-08-29 00:25:07.577975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9404acc3bc9d'
down_revision: Union[str, None] = '3a4b5c6d7e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_tg_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.create_check_constraint('check_balance_positive', 'users', 'referral_balance >= 0')
    op.create_check_constraint('check_referrals_count_positive', 'users', 'referrals_count >= 0')
    op.create_check_constraint('check_total_earned_positive', 'users', 'referral_total_earned >= 0')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'password_set_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_set_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('check_total_earned_positive', 'users', type_='check')
    op.drop_constraint('check_referrals_count_positive', 'users', type_='check')
    op.drop_constraint('check_balance_positive', 'users', type_='check')
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_tg_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    op.create_index(op.f('ix_user_sessions_user_tg_id'), 'user_sessions', ['user_tg_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###