# database/migrations/script.py.mako

"""add_exchanges_table

Revision ID: efadb2b9d87d
Revises: d5e6f7a8b9c0
Create Date: 2026-04-25 02:17:30.129514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efadb2b9d87d'
down_revision: Union[str, None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('api_key_enc', sa.String(length=500), nullable=False),
    sa.Column('api_secret_enc', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # batch_alter_table — чтобы ALTER COLUMN работал и на SQLite (copy-and-move),
    # и на PostgreSQL (native ALTER). Без batch SQLite падает с "near ALTER: syntax error".
    with op.batch_alter_table('broker_accounts') as batch_op:
        batch_op.alter_column(
            'account_name',
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=255),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_accounts') as batch_op:
        batch_op.alter_column(
            'account_name',
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )
    op.drop_table('exchanges')
    # ### end Alembic commands ###