# database/migrations/script.py.mako

"""Remove trades model

Revision ID: f33c0cf27eba
Revises: c2a3b4d5e7f8
Create Date: 2026-05-22 18:54:58.944829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33c0cf27eba'
down_revision: Union[str, None] = 'c2a3b4d5e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_index(op.f('ix_user_status'), table_name='trades')
    op.drop_table('trades')
    op.drop_constraint(op.f('uq_bot_media_key'), 'bot_media', type_='unique')
    op.drop_index(op.f('ix_bot_media_key'), table_name='bot_media')
    op.create_index(op.f('ix_bot_media_key'), 'bot_media', ['key'], unique=True)
    op.drop_constraint(op.f('uq_user_sessions_token_hash'), 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_user_sessions_token_hash'), 'user_sessions', ['token_hash'])
    op.drop_index(op.f('ix_bot_media_key'), table_name='bot_media')
    op.create_index(op.f('ix_bot_media_key'), 'bot_media', ['key'], unique=False)
    op.create_unique_constraint(op.f('uq_bot_media_key'), 'bot_media', ['key'])
    op.create_table('trades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], name=op.f('trades_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trades_pkey'))
    )
    op.create_index(op.f('ix_user_status'), 'trades', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    # ### end Alembic commands ###